version: "3.9"
services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-app-resto
    environment:
      MARIADB_ROOT_PASSWORD: admin123
      MARIADB_DATABASE: appresto
      MARIADB_USER: user
      MARIADB_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - ../mariadb-data-app-resto:/var/lib/mysql
